# Generated by Django 6.0.7 on 2026-07-28 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycloud', '0002_user_storage_path_userfile_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfile',
            name='file_path',
        ),
    ]
